# config.py

# --- GAME MECHANICS CONFIG (Currently only used by server.py) ---
WORLD_WIDTH = 800
WORLD_HEIGHT = 600
#TITLE = "SpaceWar 2"

TICK_RATE = 60
SUN_RADIUS = 30
SUN_MASS = 5000
GRAVITY_CONSTANT = 1000
SHIP_MASS = 1
SHIP_THRUST = 200
SHIP_ROTATION_SPEED = 3.0
SHIP_RADIUS = 15
BULLET_SPEED = 300
BULLET_LIFETIME = 3.0
BULLET_RADIUS = 3
